### ISSUE TITLE
Installation via npm@5 fails

### ISSUE THREAD

**Issue by ryym** [interfirm/configs#14]
- [Travis log](https://travis-ci.org/interfirm/configs/builds/237752742)
- [npm@5 release note](http://blog.npmjs.org/post/161081169345/v500)

[ログ](https://travis-ci.org/interfirm/configs/builds/237752742#L557) を見ると`shrinkwrap.js`というところで失敗している。v5 から導入された`package-lock.json`周りの挙動と相性が悪い..?

**Comment by ybiquitous** [comment]
@ryym 一時的にNode.jsのバージョン落とした方が良さげですか？

**Comment by ryym** [comment]
@ybiquitous その方が良さそうですね。7に固定すればテストが通りました。
npm側の問題なのかどうかはもう少し調べる必要がありそうです。

**Comment by ybiquitous** [comment]
@ryym 👇 のように修正すると `npm install` は通りましたが、`postinstall` フックが実行されないみたいです 😓 （よーわからん 😢 ）
```
diff --git a/install.test.sh b/install.test.sh
index 3080db7..8cdf780 100755
--- a/install.test.sh
+++ b/install.test.sh
@@ -20,7 +20,7 @@ assert() {
   test -f .rubocop.base.yml
 }
 
-npm install --no-progress --save-dev "file:$(dirname $(pwd))"
+npm install --no-progress --save-dev ..
 cat package.json
 assert
 
```

とりあえず、Node.js v7 でいいと思います 👍

**Comment by ryym** [comment]
@ybiquitous 調査ありがとうございます!  不思議な挙動ですね。。
自分も時間ある時に調べてみます。
