### ISSUE TITLE
rubocop: Is Style/NumericPredicate necessary?

### ISSUE THREAD

**Issue by ryym** [interfirm/configs#69]
RuboCop の [Style/NumericPredicate](http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/NumericPredicate) という Cop が`a > 0`のようなコードを一律で`a.positive?`に変えろと怒るんですが、このルールって必要でしょうか..?

文字数的にも前者の方が少ないし、個人的には前者のコードで何も問題ないように感じます。`a == 0` -> `a.zero?`の変換に関しては、`a`が nil や数値以外の値であるケースについて意識せざるを得なくなるので、意味が無くはないかなとは思いますけど。

**Comment by ybiquitous** [comment]
@ryym 
もしかしたら `0` がマジックナンバーなのがイヤなのではないでしょうか？
個人的にはどちらでも許可するようにしておけばよいかと思います（あまり拘りはないです）。

（ただし、スタイルに関しては拘りだすとキリがないことを付け加えておきます 😅 ）

**Comment by ryym** [comment]
> スタイルに関しては拘りだすとキリがないことを付け加えておきます

まさしくそうですね。なので別に`> 0`や`== 0`に統一しようという話じゃなくて、この Cop を disabled にして、どちらでも文脈的に良さげな方を使えばいいじゃん、という Issue でした。

**Comment by ybiquitous** [comment]
いいと思います 👍
